import Image from 'next/image';
import Head from "next/head";
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useState } from "react";
import { GlobeAltIcon, UserCircleIcon, UserIcon, MagnifyingGlassIcon } from "@heroicons/react/24/solid";

type Props = {
  placeholder: string
}

export default function Header({placeholder}: Props) {
  const [searchInput, setSearchInput] = useState("");
  const [numOfGuests, setNumOfGuests] = useState(1);
  const router = useRouter();

  // Push data out to result page
  const search = async () => {
    await router.push({
      pathname: "/result",
      query: {
        location: searchInput,
        checkIn: "",
        checkOut: "",
        guest: numOfGuests
      }
    });
  };

  return (
    <header className='sticky top-0 z-50 flex flex-wrap gap-3 grid-cols-2 md:grid md:grid-cols-3 bg-beige shadow-md p-5 md:px-10'>
      <Head>
        <title>Travel Oasis</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link className='relative flex items-center cursor-pointer my-auto' href="/">
        <Image src='/travel-temple-website-favicon-color.svg' alt="logo" width={50} height={50} />
        <h1 className='hidden sm:inline-block self-center text-xl font-semibold whitespace-nowrap text-black'>Travel Oasis</h1>
      </Link>
      <div className='flex-grow items-center border-2 md:shadow-sm rounded-full py-3'>
        <input 
          className='flex-grow pl-4 bg-transparent outline-none text-sm text-gray-600 placeholder-gray-400 w-[97%]' 
          placeholder={placeholder || "Where to..."}
          type="text" 
          value={searchInput}
          onChange={(e) => setSearchInput(e.target.value)}
        />
      </div>
      <div className='hidden md:flex items-center space-x-4 justify-end text-gray-500'>
        <p className='hidden lg:inline cursor-pointer'>Want to be a Host?</p>
        <GlobeAltIcon className='h-6 cursor-pointer'/>
        <div className='flex items-center space-x-2 border-2 p-2 rounded-full border-[#883D1A]'>
          <UserCircleIcon className='h-6' />
        </div>
      </div>
      {searchInput && (
        <div>

        </div>
      )}
    </header>
  )
}